name: oq_yol
description: "Oq yo'l"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter

  # for design_system
  l: ^4.0.2
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.1
  lottie: ^3.1.2
  bulleted_list: ^0.0.1+0.1a

  # for slides
  carousel_slider: ^4.2.1

  # circular percentage indicator
  percent_indicator: ^4.2.3

  #Utils
  device_preview: ^1.1.0

  #formatters
  intl_phone_field: ^3.1.0
  smooth_page_indicator: ^1.1.0
  mask_text_input_formatter: ^2.9.0
  easy_stepper: ^0.8.4
#  google_fonts: ^6.2.1

  #for locale storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3


  #for state management
  flutter_riverpod: ^2.4.10

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # for Network
  dio: ^5.4.1
  connectivity_plus: ^6.0.3

  # firebase
  firebase_core: ^2.25.5
  firebase_crashlytics: ^3.5.5
  firebase_analytics: ^10.10.5
  firebase_remote_config: ^4.4.5

  #for navigation
  go_router: ^14.1.1

  # meta
  package_info_plus: ^8.0.0
  meta: ^1.11.0

  #biometricx:
  local_auth: ^2.2.0
  local_auth_android: ^1.0.38
  local_auth_darwin: ^1.3.0

  #for youtube video
#  youtube_player_flutter: ^9.0.1

  #for view:
  webview_flutter: ^4.7.0
  webview_flutter_wkwebview: ^3.13.1
  webview_flutter_android: ^3.16.4

  #for pdf files
  syncfusion_flutter_pdfviewer: ^24.2.8
  flutter_windowmanager: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/



  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.otf

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/l10n
  template-arb-file: intl_en.arb
  output-localization-file: app_localizations.dart
  use_deferred_loading: false